### ISSUE TITLE
Previous state of edited activity/accommodation is incorrect when shown in GUI

### ISSUE THREAD

**Issue by 1nefootstep** [AY1920S1-CS2103T-T09-1/main#137]
During a `edit activity/accommodation` command, if the activity or accommodation has its contact, the GUI shown on the `Edited from:` card will be incorrect and already show the edited contact.

**Comment by ernestyyh** [comment]
Edit activity currently works as intended. The edited from display shows the correct card. Edit accommodation currently has some other issues which prevent testing of this bug.

**Comment by 1nefootstep** [comment]
Tested both editing activity/accommodation contacts. Seems to be working fine now. Closing.
