### ISSUE TITLE
Tags in appointment shown on itinerary might be truncated when there isn't enough space

### ISSUE THREAD

**Issue by 1nefootstep** [AY1920S1-CS2103T-T09-1/main#140]
![image](https://user-images.githubusercontent.com/26926388/67990936-6c013300-fc72-11e9-8039-45cddfbd26c7.png)

**Comment by ernestyyh** [comment]
Looks like 120mins is the minimum to view a simple card. A `view day` command would be helpful.

**Comment by 1nefootstep** [comment]
Implemented `list day`.
