### ISSUE TITLE
Fix autoschedule bugs

### ISSUE THREAD

**Issue by oscarsu97** [AY1920S1-CS2103T-T09-1/main#195]
There might be wrong intepretation for autoschedule if for e.g, t/CS 2103 could be wrongly intepreted  as a `tag`  named `CS` and time `2103`, where instead user could meant a `tag` named that is named `CS 2103`

**Comment by 1nefootstep** [comment]
Perhaps banning spaces in tags is the right way to go

**Comment by oscarsu97** [comment]
Done
