### ISSUE TITLE
Undo Bug 

### ISSUE THREAD

**Issue by seanlowjk** [AY1920S1-CS2103T-T09-1/main#259]
Users are allowed to do `undo undo undo`, assuming that `undo` command will be run three times. 

However, when I tried to `undo undo undo`, the undo command only works one time. 

Suggestion: 
1) `undo undo undo` is not allowed. `undo` and `redo` should only be called ONCE. 
2) the number of times you call `undo` is the number of times the system gets undone. Same for `redo`.

**Comment by OneArmyj** [comment]
yea it only calls once O.O

**Comment by KxxMxxx** [comment]
No
